### ISSUE TITLE
Portal columns are collapsed with first-time page visit

### ISSUE THREAD

**Issue by noni-mizu** [noni-mizu/Akvopedia_App#1]
Suggestion: change the default so the dropdown menu is expanded on the first visit. If users want to collapse it, they can. But the portal columns are the most important part of the portal, so they need to be visible.

The dropdown widget can be seen below, where it says "More information...".

![portal dropdown menu](https://cloud.githubusercontent.com/assets/3211658/22810363/1d32a424-eeed-11e6-9a23-5626942893c1.png)

**Comment by MelEnt** [comment]
This is a setting in the bundle.js file in https://github.com/noni-mizu/Akvopedia_App/blob/master/app/src/main/assets/bundle.js

To set initial visibility of the boxes, change:
- https://github.com/noni-mizu/Akvopedia_App/blob/master/app/src/main/assets/bundle.js#L887  to tables[i].style.display = 'block';
- - https://github.com/noni-mizu/Akvopedia_App/blob/master/app/src/main/assets/bundle.js#L889  to bottomDiv.style.display = 'none';

**Comment by noni-mizu** [comment]
Works like a charm, thank you!
